const $=s=>document.querySelector(s);const screens={title:$('#title-screen'),game:$('#game-screen'),letter:$('#letter-screen')};
const chapters=[
 {id:'garden',label:'CHAPITRE I',title:'Le jardin se souvient',text:"Le soir a déposé une brume douce sur le jardin. Trois lumières veillent entre les arbres. Elles semblent attendre que tu les réveilles…",action:'lanterns'},
 {id:'observatory',label:'CHAPITRE II',title:'Ce que les étoiles écrivent',text:"Derrière la porte, l'ancien observatoire respire encore. Sur le cuivre, une phrase est gravée : « Ce qui brille le plus n'est pas toujours le plus haut. »",action:'constellation'},
 {id:'greenhouse',label:'CHAPITRE III',title:'La serre des possibles',text:"La dernière pièce est pleine de feuillages et de souvenirs. Au centre, une enveloppe repose sous une fleur blanche. Mais elle ne s'ouvre qu'à celle qui connaît le chemin.",action:'final'}
];
let state=JSON.parse(localStorage.getItem('lohen-progress')||'null')||{chapter:0,lanterns:[],stars:[],sound:false};let audio;
function save(){localStorage.setItem('lohen-progress',JSON.stringify(state));}
function show(s){Object.values(screens).forEach(x=>x.classList.remove('active'));s.classList.add('active')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function renderTitle(){show(screens.title);$('#continue').classList.toggle('hidden',state.chapter===0&&!state.lanterns.length)}
function render(){show(screens.game);const c=chapters[state.chapter];$('#chapter-label').textContent=c.label;$('#progress-bar').style.width=`${(state.chapter+1)*33.33}%`;const scene=$('#scene');scene.className='scene '+c.id;scene.innerHTML='';$('#story').innerHTML=`<h2>${c.title}</h2><p>${c.text}</p>`;const controls=$('#controls');controls.innerHTML='';if(c.action==='lanterns')renderLanterns(scene,controls);if(c.action==='constellation')renderStars(scene,controls);if(c.action==='final')renderFinal(scene,controls)}
function renderLanterns(scene,controls){['l1','l2','l3'].forEach((cl,i)=>{const b=document.createElement('button');b.className='lantern '+cl+(state.lanterns.includes(i)?' found':'');b.innerHTML=`<span>${state.lanterns.includes(i)?'éveillée':'lumière'}</span>`;b.onclick=()=>{if(state.lanterns.includes(i))return;const expected=state.lanterns.length;if(i!==[1,0,2][expected]){toast('Écoute le rythme de la nuit…');return}state.lanterns.push(i);save();render();if(state.lanterns.length===3)toast('Les trois lumières montrent le chemin.')};scene.appendChild(b)});const p=document.createElement('p');p.className='hint';p.textContent=state.lanterns.length?`${state.lanterns.length} / 3 lumière éveillée${state.lanterns.length>1?'s':''}`:'Indice : la lumière la plus haute appelle en premier.';controls.appendChild(p);if(state.lanterns.length===3){const b=document.createElement('button');b.className='solve';b.textContent='Suivre le chemin →';b.onclick=()=>{state.chapter=1;save();render()};controls.appendChild(b)}}
function renderStars(scene,controls){const c=document.createElement('div');c.className='constellation';c.innerHTML='✦<br>·  ✧  ·';scene.appendChild(c);const p=document.createElement('p');p.className='hint';p.textContent='Replace les étoiles de la plus haute à la plus basse.';controls.appendChild(p);const grid=document.createElement('div');grid.className='puzzle-grid';['✦','✧','·'].forEach((v,i)=>{const b=document.createElement('button');b.textContent=v;b.setAttribute('aria-label','Étoile '+(i+1));if(state.stars.includes(i))b.classList.add('selected');b.onclick=()=>{if(state.stars.includes(i))return;state.stars.push(i);save();render()};grid.appendChild(b)});controls.appendChild(grid);if(state.stars.length===3){const b=document.createElement('button');b.className='solve';b.textContent='Ouvrir la voûte →';b.onclick=()=>{state.chapter=2;save();render()};controls.appendChild(b)} }
function renderFinal(scene,controls){const plant=document.createElement('div');plant.className='plant';plant.textContent='✾';scene.appendChild(plant);const p=document.createElement('p');p.className='hint';p.textContent='Un dernier geste : touche la fleur qui a gardé la lumière.';controls.appendChild(p);const b=document.createElement('button');b.className='solve';b.textContent='Cueillir la fleur blanche';b.onclick=()=>showLetter();controls.appendChild(b)}
function showLetter(){show(screens.letter);$('#letter-content').innerHTML=`<p>Ma Lohen,</p><p>Si tu lis ces mots, c'est que tu as suivi les petites lumières que j'ai laissées sur ton chemin. J'aurais pu te donner cette lettre directement, mais je voulais t'offrir quelques minutes hors du temps — un endroit rien qu'à toi, rempli de douceur, de mystère et de souvenirs.</p><p>Chaque énigme était une façon de te dire que j'aime ta curiosité, ta force et la lumière que tu apportes autour de toi. Merci d'être toi, simplement. J'espère que tu garderas de cette aventure le sentiment d'avoir été accompagnée, pensée, et aimée à chaque étape.</p><p>Avec tout mon cœur,<br><strong>Esteban</strong></p><h1>Je t'aime ❤️</h1><p><strong>J'espère que tu as apprécié mon cadeau.</strong></p>`;state.finished=true;save()}
function reset(){state={chapter:0,lanterns:[],stars:[],sound:false};save();$('#menu').classList.add('hidden');renderTitle();toast('L’aventure peut recommencer.')}
function toggleAudio(){state.sound=!state.sound;save();if(state.sound){audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=196;g.gain.value=.018;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+1);toast('Un souffle accompagne tes pas.')}else toast('Le silence revient.')}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='new'){state={chapter:0,lanterns:[],stars:[],sound:state.sound};save();render()}if(a==='continue'){if(state.finished)showLetter();else render();}if(a==='menu')$('#menu').classList.remove('hidden');if(a==='close-menu'||a==='resume')$('#menu').classList.add('hidden');if(a==='reset'&&confirm('Effacer toute la progression ?'))reset();if(a==='sound')toggleAudio();if(a==='restart'){state={chapter:0,lanterns:[],stars:[],sound:state.sound};save();renderTitle()}});renderTitle();
